import type { Book, OtherHobby, Skill, SportsActivity, WorkExperience } from '@/types';

export const aboutStats = [
  { number: '5', label: 'Years Exp' },
  { number: '2', label: 'AU Clients' },
  { number: '10+', label: 'Projects' },
];

export const personalTags = [
  { icon: '📍', text: 'Chengdu, China' },
  { icon: '🗓️', text: 'Born in the 90s' },
  {
    icon: '🌏',
    text: 'Worked with Australian clients at a global tech firm — fluent in English tech docs & async comms.',
  },
  {
    icon: '💡',
    text: 'Obsessed with building things that feel alive — in code, in books, and on the court.',
  },
];

export const education = {
  school: '电子科技大学成都学院',
  degree: 'Bachelor of Computer Science (Top-up)',
  period: '2018 — 2020',
};

export const workExperiences: WorkExperience[] = [
  {
    id: 'cit',
    tag: 'Global Tech · Australia',
    leftTitle: '为真实用户\n构建真实产品',
    color: '#C4714B',
    period: 'Oct 2022 — Jul 2025',
    company: 'CI&T',
    role: 'Mid-Level Frontend Engineer · 中级前端工程师',
    location: 'Chengdu → Remote (AU clients)',
    body: '在全球技术咨询公司 CI&T 担任前端工程师，服务澳大利亚头部客户，涵盖旅游、保险等行业。深度参与三个核心项目的重构与迭代，在 Next.js、Turborepo、Storybook 等现代工程体系中积累了大型项目实战经验。',
    highlights: [
      '主导 TravelAssociates 平台全量迁移，适配 Next.js + Turborepo 架构，按时交付关键前端功能',
      '基于 Storybook 搭建标准化 UI 组件库，实现与 Figma 设计稿 100% 还原，统一全站视觉规范',
      '优化关键渲染路径，Lighthouse SEO 达满分 100/100，Performance 达 89/100',
      '使用 Framer Motion 实现品牌级高保真交互动效，提升用户参与度并保障跨端稳定性',
      '在 Flight Centre Lerna Monorepo 中开发可复用业务组件，打通 Drupal Headless CMS 与前端映射层，支持编辑器拖拽建页',
      '集成 AWS Lambda + Elasticsearch Serverless BFF，为门店搜索功能提供高性能数据聚合，编写并维护 OpenAPI (Swagger) 规范',
      '为 CoverMore 白标保险产品实现多步购买漏斗，设计支持多品牌定制的白标架构，单一代码库服务多个合作伙伴',
    ],
    techStack: [
      'React 18',
      'Next.js',
      'TypeScript',
      'Turborepo',
      'Storybook',
      'Framer Motion',
      'AWS Lambda',
      'Elasticsearch',
      'Drupal CMS',
      'GitHub Actions',
    ],
    illustrationKey: 'architecture',
  },
  {
    id: 'qingcloud',
    tag: 'Cloud · SaaS Platform',
    leftTitle: '云市场的\n每一个像素',
    color: '#6B8F71',
    period: 'Aug 2021 — Jun 2022',
    company: 'QingCloud',
    role: 'Frontend Engineer · 前端工程师',
    location: '成都',
    body: '在青云科技负责云市场（Marketplace）前端研发，覆盖买家中心、卖家中心、订单管理、支付流程等核心业务链路，并主导企业官网的移动端响应式改版，积累了 ToB SaaS 产品的完整开发经验。',
    highlights: [
      '使用 React + TypeScript 端到端交付云市场买卖家中心功能，包括订单管理与支付流程',
      '主导高流量营销落地页开发，使用 Next.js SSR 保障 SEO 效果与首屏性能，提升用户转化率',
      '执行企业官网全面移动端优先响应式改版，确保跨设备无障碍访问体验',
    ],
    techStack: ['React', 'TypeScript', 'Next.js', 'Ant Design', 'Sass', 'RESTful API'],
    illustrationKey: 'dataviz',
  },
  {
    id: 'pengye',
    tag: 'Early Career · Framework',
    leftTitle: '从框架出发\n理解工程本质',
    color: '#7A9DB5',
    period: 'Oct 2019 — Jul 2021',
    company: 'Pengye Software',
    role: 'Frontend Engineer · 前端工程师',
    location: '成都',
    body: '职业生涯的起点。在鹏业软件深度参与跨平台 UI 框架的从零设计与研发，独立完成 Angular 框架搭建并发布为内部 npm 包，负责多角色动态仪表盘和复杂权限系统的实现。',
    highlights: [
      '使用 Angular 9 构建跨平台 UI 框架（PC + 微信小程序），封装为内部 npm 包供多项目复用',
      '使用位运算实现读/写/审批/编辑的复杂权限控制体系，显著降低逻辑耦合度和内存开销',
      '设计多角色动态仪表盘与全局搜索模块，实现关键词高亮和搜索历史功能',
    ],
    techStack: ['Angular 9', 'TypeScript', 'WeChat Mini-program', 'npm Package', 'RxJS', 'Less'],
    illustrationKey: 'ecommerce',
  },
];

export const skills: Skill[] = [
  {
    icon: '⚡',
    name: 'React & Next.js',
    category: 'frontend',
    level: 0.95,
    desc: 'React 18 Hooks、Next.js SSR/App Router 生产级实战',
    tags: ['React 18', 'Next.js', 'Framer Motion', 'React Query'],
  },
  {
    icon: '🔷',
    name: 'TypeScript',
    category: 'frontend',
    level: 0.92,
    desc: 'Type-safe 开发，泛型、工具类型熟练运用',
    tags: ['TypeScript', 'Zod', 'Type Guards', 'Generics'],
  },
  {
    icon: '🎨',
    name: 'CSS & 组件库',
    category: 'frontend',
    level: 0.92,
    desc: 'Tailwind CSS、Material UI、Ant Design、CSS-in-JS',
    tags: ['Tailwind CSS', 'Material UI', 'Ant Design', 'Sass/Less'],
  },
  {
    icon: '📖',
    name: 'Storybook',
    category: 'frontend',
    level: 0.88,
    desc: '组件驱动开发，视觉测试，100% Figma 还原',
    tags: ['Storybook', 'Visual Testing', 'Design System', 'Figma'],
  },
  {
    icon: '🏗️',
    name: 'Monorepo 工程化',
    category: 'engineering',
    level: 0.88,
    desc: 'Turborepo / Lerna，跨项目组件共享与发布',
    tags: ['Turborepo', 'Lerna', 'npm Package', 'Vite/Webpack'],
  },
  {
    icon: '☁️',
    name: 'Full-stack & Cloud',
    category: 'engineering',
    level: 0.78,
    desc: 'AWS Lambda Serverless BFF，Nginx，Linux',
    tags: ['AWS Lambda', 'Elasticsearch', 'Nginx', 'Linux'],
  },
  {
    icon: '🧪',
    name: '测试 & CI/CD',
    category: 'engineering',
    level: 0.8,
    desc: 'Jest 单测，GitHub Actions，OpenAPI 规范',
    tags: ['Jest', 'GitHub Actions', 'OpenAPI/Swagger', 'Code Review'],
  },
  {
    icon: '🤝',
    name: '协作 & 交付',
    category: 'engineering',
    level: 0.93,
    desc: 'Agile/Scrum，全链路 Ticket 所有权，跨国团队',
    tags: ['Agile/Scrum', 'Jira', 'Confluence', 'Figma', 'Slack'],
  },
  {
    icon: '🌏',
    name: 'Cross-timezone Collaboration',
    category: 'soft',
    level: 0.92,
    desc: '长期与澳洲客户团队远程协作，熟悉异步沟通节奏与英文工作流',
    tags: ['Remote-first', 'Async Comms', 'English Workflow', 'AU Clients'],
  },
  {
    icon: '🤝',
    name: '跨团队沟通',
    category: 'soft',
    level: 0.9,
    desc: '成都 · 武汉 · 北京多地协作，推动技术方案对齐与产品需求落地',
    tags: ['多地协作', '需求对齐', '方案评审', '线上会议'],
  },
  {
    icon: '🎯',
    name: '需求理解与交付',
    category: 'soft',
    level: 0.93,
    desc: '从 PRD 到上线全链路独立负责，准确拆解需求、识别风险、按时交付',
    tags: ['PRD 理解', '任务拆解', '风险识别', '准时交付'],
  },
  {
    icon: '🧩',
    name: 'Design-Dev 协作',
    category: 'soft',
    level: 0.88,
    desc: '深度对接 Figma 设计稿，与设计师高效沟通还原细节，建立组件规范',
    tags: ['Figma', '像素还原', '组件规范', '设计对齐'],
  },
];

export const bookshelf: Book[] = [
  {
    title: '我与地坛',
    author: '史铁生',
    color: '#8B6F47',
    category: '文学·散文',
    year: 2023,
    note: '在最狂妄的年龄忽地残废了双腿，史铁生在地坛里想通了很多事。读完很久，还是会想起那句"死是一件不必急于求成的事"。',
    doubanUrl: 'https://book.douban.com/subject/1054187/',
  },
  {
    title: '悉达多',
    author: '赫尔曼·黑塞',
    color: '#C4714B',
    category: '文学·小说',
    year: 2024,
    note: '不是关于佛陀的故事，而是关于一个人如何找到自己的道路。每次人生迷茫时翻一遍，都会有新的理解。',
    doubanUrl: 'https://book.douban.com/subject/26980487/',
  },
  {
    title: '西方现代思想讲义',
    author: '刘擎',
    color: '#4A6741',
    category: '哲学·思想',
    year: 2024,
    note: '把尼采、韦伯、萨特讲得通透又不失严谨。读完对"现代性的困境"有了具体的感知，而不只是一个词。',
    doubanUrl: 'https://book.douban.com/subject/35313227/',
  },
  {
    title: '可能性的艺术',
    author: '刘瑜',
    color: '#7A9DB5',
    category: '政治·社会',
    year: 2023,
    note: '比较政治学入门，但写得像散文。刘瑜用"可能性"这个词，提醒我们历史没有必然，只有选择。',
    doubanUrl: 'https://book.douban.com/subject/35819419/',
  },
  {
    title: '存在主义是一种人道主义',
    author: '萨特',
    color: '#2C3E50',
    category: '哲学·思想',
    year: 2023,
    note: '"存在先于本质"——我们先来到世界，然后定义自己。薄薄一本，却是理解萨特最好的入口。',
    doubanUrl: 'https://book.douban.com/subject/5256578/',
  },
  {
    title: '看不见的女性',
    author: '卡罗琳·克里亚多·佩雷斯',
    color: '#9B4D7E',
    category: '社会·性别',
    year: 2024,
    note: '数据里的性别偏见。从城市规划到医疗研究，原来世界的默认设置是"男性"。读完会重新审视很多习以为常的事。',
    doubanUrl: 'https://book.douban.com/subject/35074637/',
  },
  {
    title: '1984',
    author: '乔治·奥威尔',
    color: '#3D3D3D',
    category: '文学·小说',
    year: 2022,
    note: 'Big Brother is watching you. 写于1949年，读起来像是在描述某些现实。有些书让人不舒服，但必须读。',
    doubanUrl: 'https://book.douban.com/subject/4820710/',
  },
  {
    title: '现代艺术150年',
    author: '威尔·贡培兹',
    color: '#C9A84C',
    category: '艺术·设计',
    year: 2024,
    note: '从塞尚到班克斯，用讲故事的方式把现代艺术串联起来。不再觉得当代艺术故弄玄虚，开始真正"看懂"了。',
    doubanUrl: 'https://book.douban.com/subject/25902848/',
  },
  {
    title: '始于极限',
    author: '上野千鹤子 · 铃木凉美',
    color: '#A0522D',
    category: '社会·性别',
    year: 2024,
    note: '一场关于女性、欲望、自由与妥协的真实对话。两个截然不同的女人，在信件往来里碰撞出很多让人久久回味的问题。',
    doubanUrl: 'https://book.douban.com/subject/36154656/',
  },
  {
    title: '春天终将来临',
    author: '大卫·霍克尼 · 马丁·盖福特',
    color: '#4A7C59',
    category: '艺术·设计',
    year: 2024,
    note: '霍克尼用 iPad 画画，用摄影机记录四季。这本书让我重新看待"观看"这件事——不只是用眼睛，而是用时间和记忆。',
    doubanUrl: 'https://book.douban.com/subject/35815393/',
  },
  {
    title: '祥瑞',
    author: '月望东山',
    color: '#8B6914',
    category: '历史',
    year: 2024,
    note: '写王莽和他的时代。一个被史书钉在"篡汉"二字上的人，读完才发现他更像一个理想主义者——结局是悲剧，但过程耐人寻味。',
    doubanUrl: 'https://book.douban.com/subject/36672955/',
  },
  {
    title: '金阁寺',
    author: '三岛由纪夫',
    color: '#7A6A4A',
    category: '文学·小说',
    year: 2023,
    note: '一个对美近乎病态的人，最终选择亲手毁掉他所爱的美。三岛的文字本身就是金阁，华丽、精确、令人不安。',
    doubanUrl: 'https://book.douban.com/subject/26986954/',
  },
  {
    title: '反脆弱',
    author: '纳西姆·尼古拉斯·塔勒布',
    color: '#5B7FA6',
    category: '哲学·思想',
    year: 2024,
    note: '不只是"抗压"，而是从混乱中获益。读完重新审视了自己对不确定性的态度——与其回避波动，不如让自己从中变得更强。',
    doubanUrl: 'https://book.douban.com/subject/25782902/',
  },
];

export const sportsActivities: SportsActivity[] = [
  {
    id: 'pickleball',
    name: 'Pickleball',
    icon: '🎾',
    color: '#C4714B',
    tagline: 'Twinkle Pickle · Beesoul 签约战队球员',
    desc: '组建业余战队 Twinkle Pickle，代表 Beesoul 品牌参加比赛。从上海到重庆到吉隆坡，用一块球场和一把球拍，认识了一群真正热爱这项运动的人。',
    badges: ['Twinkle Pickle 战队', 'Beesoul 签约球员', '上海 · 重庆 · 吉隆坡'],
    photos: [
      { label: '个人训练' },
      { label: '上海站 · 比赛' },
      { label: '重庆站 · 战队' },
      { label: '吉隆坡站 · 海外赛' },
      { label: '队友合照' },
      { label: 'Beesoul 装备' },
    ],
  },
];

export const otherHobbies: OtherHobby[] = [
  {
    icon: '🎭',
    label: '音乐剧',
    color: '#9B4D7E',
    desc: '尤其爱《莫里哀》和《剧院魅影》。当演员开口的那一刻，舞台上所有的光和声音都只为一种情感服务——那是电影给不了的东西。',
    photos: [
      { label: '莫里哀', src: '' },
      { label: '剧院魅影', src: '' },
      { label: '现场留念', src: '' },
    ],
  },
  {
    icon: '🎬',
    label: '电影',
    color: '#5B7FA6',
    desc: '在观影团看电影——字幕播完才开灯，没有人提前离席。这群人真正尊重电影，我也在这里学会了怎么"看"一部电影。',
  },
  {
    icon: '🍳',
    label: '做饭',
    color: '#C4714B',
    desc: '川菜是母语，但我也迷上了做意大利面和日式拉面。料理和写代码一样——细节决定成败，而且立刻就能得到反馈。',
  },
  {
    icon: '✈️',
    label: '旅行',
    color: '#C9A84C',
    desc: '去过的地方越多，越觉得世界很大、偏见很小。每次旅行都会带回一些新的问题，而不只是答案。',
    photos: [
      { label: '旅途照片', src: '' },
      { label: '旅途照片', src: '' },
      { label: '旅途照片', src: '' },
    ],
  },
  {
    icon: '🎾',
    label: '网球',
    color: '#7A9D5B',
    desc: '打网球让我重新理解了"节奏"这件事。发球、回击、移步——每一拍都是当下，没有办法分心。场上的专注感和写代码时很像。',
  },
  {
    icon: '🛹',
    label: '陆冲',
    color: '#4A6741',
    desc: '从零开始自学，带动了一圈朋友一起玩，最后自学上了泵道。那种靠自己找到节奏感、然后带着大家一起飞起来的感觉，很难复制。',
  },
  {
    icon: '🚴',
    label: '骑行',
    color: '#7A9DB5',
    desc: '城市里的慢骑是解压神器，长途骑行是另一种旅行方式。两个轮子，足够看见很多平时错过的风景。',
  },
  {
    icon: '🖊️',
    label: 'Penbeat',
    color: '#B8935A',
    desc: '用一支笔打出节奏——成本极低，门槛极高。曾经认真练过一阵，也许是我所有爱好里最冷门的一个，但恰好证明：有趣的事不需要理由。',
  },
];
